CafeApplication.Web/Models/ErrorViewModel.cs
using System;

namespace CafeApplication.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CafeApplication.Web/Models/TypeBoisson.cs
using System;
using System.Collections.Generic;
using System.Text;

namespace CafeApplication.Web.Models
{
    public enum TypeBoisson : int
    {
        Cafe = 1,

        Chocolat = 2,

        LeThe = 3
    }
}

CafeApplication.Web/Models/TypeBoissonViewModel.cs
using CafeApplication.Web.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace CafeApplication.Web.Models
{
    public class TypeBoissonViewModel 
    {

        [DisplayName("Select Consommateur")]
        public virtual int ConsommateurID { get; set; }

        [DisplayName("Type de Boisson")]
        public virtual TypeBoisson TypeBoisson { get; set; }
        [DisplayName("Nombre de cuillere")]
        public virtual int NombreCuilliere { get; set; }

        [DisplayName("Utilisation de ton Propre Mug")]
        public virtual bool PropreMug { get; set; }

        [DisplayName("Utilisation du Badge")]
        public virtual bool DerniereSelection { get; set; }

    }
}

CafeApplication.Web/Controllers/ConsommateurController.cs
using CafeApplication.Service.Service;
using Microsoft.AspNetCore.Mvc;

namespace CafeApplication.Controllers
{
    [Route("api/[controller]")]
    public class ConsommateurController : Controller
    {

        /// <summary>
        /// Variables de travail
        /// </summary>
        private IService _serv;

        /// <summary>
        /// Constructeur
        /// </summary>
        /// <param name="serv"></param>
        public ConsommateurController(IService serv)
        {
            
            _serv = serv;

        }

        // GET api/values
        [HttpGet]
        public IActionResult Get()
        {
            //return _repoConsommateur.GetAll();
            return Ok(_serv.ObtenirConsommateurAll());

        }


        

        // GET api/values/5
        [HttpGet("{id}")]
        public IActionResult Get(int id)
        {
            //return _repoConsommateur.Get(id);
            return Ok(_serv.ObtenirConsommateur(id));
        }

        

        

        
    }
}

CafeApplication.Web/Controllers/ConsommationController.cs
using System.Collections.Generic;
using AutoMapper;
using CafeApplication.Service.Factory.Interfaces;
using CafeApplication.Service.Service;
using CafeApplication.Web.Models;
using Microsoft.AspNetCore.Mvc;


namespace CafeApplication.Controllers
{
    [Route("api/[controller]")]
    public class ConsommationController : Controller
    {
        /// <summary>
        /// Variable de travail
        /// </summary>
        private IService _serv;
        private IMapper _mapper;
        
        /// <summary>
        /// Constructeur
        /// </summary>
        /// <param name="serv"></param>
        /// <param name="mapper"></param>
        public ConsommationController(IService serv, IMapper mapper)
        {
            _serv = serv;
            _mapper = mapper;

        }


        // GET api/values
        [HttpGet]
        public IActionResult Get()
        {

            return Ok(_mapper.Map<IEnumerable<TypeBoissonViewModel>>(_serv.ObtenirConsommationAll()));
            
        }

        [HttpGet("{id}")]
        public IActionResult Get(int id)
        {

            return Ok(_mapper.Map<TypeBoissonViewModel>(_serv.ObtenirDerniereConsommationParClient(id)));

        }



        // POST api/values
        [HttpPost]
        public IActionResult Post([FromBody]TypeBoissonViewModel cons)
        {
            _serv.AjouterConsommation(_mapper.Map<IBreuvage>( cons), 1);
            
            return Ok(cons);


        }

        
    }
}

CafeApplication.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CafeApplication.Web.Models;

namespace CafeApplication.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CafeApplication.Web/Views/Home/Index.cshtml
<!DOCTYPE html>
@using CafeApplication.Web.Models
@model TypeBoissonViewModel


<html lang="en">

<head>

    <title>ASP.NET Web API - Issam</title>

    <link href="~/css/site.css" rel="stylesheet" />

    <script src="~/js/jquery-3.3.1.min.js"
            type="text/javascript"></script>

    <script type="text/javascript">

        $(document).ready(function () {


            $.getJSON('api/consommateur/', function (data) {

                //clear the current content of the select
                $('#Consommateurs').empty();


                $('#Consommateurs').append('<option value=0>-Please select-</option>');
                //iterate over the data and append a select option
                $.each(data, function (i, item) {
                    $('#Consommateurs').append('<option value=' + item.id + '>' + item.prenom + ' ' + item.nom + '</option>');
                })
            });

        });

        function RecupererBadge() {

            if ($('#Consommateurs').val() != 0) {
                $.getJSON('api/consommateur/' + $('#Consommateurs').val(), function (data) {
 
                    if (data.derniereSelection == true) {
                        
                        Modifier();
                     
                    }

                });

            }
            
        };

        function Enum(valueMap) {
            // We store the enumeration object
            this._valueMap = valueMap;
            this._valueToLabelMap = {};
            var that = this;

            // This will create an inverse map: values to labels
            Object.keys(valueMap).forEach(function (label) {
                that._valueToLabelMap[valueMap[label]] = label;
            });
        };

        Enum.prototype = {
            // Getting the whole label is as simple as accessing
            // the inverse map where values are the object properties!
            getLabel: function (value) {
                if (this._valueToLabelMap.hasOwnProperty(value)) {
                    return this._valueToLabelMap[value];
                } else {
                    throw Error("Enum instance has no defined '" + value + "' value");
                }
            }
        };

        var myEnum = new Enum({
            Cafe: 1,

            Chocolat: 2,

            LeThe: 3,
        });

        function Modifier()
        {
            
            $.getJSON('api/consommation/' + $('#Consommateurs').val(), function (data1) {

                $('#TypeBoisson').val(myEnum.getLabel(data1.typeBoisson) );
                $('#NombreCuillere').val(data1.nombreCuilliere);
                $("#PropreMug").prop("checked", data1.propreMug);
 
            });


        };

        function ajouter() {
            var model = new FormData($('form'));
            
            model.ConsommateurID = $('#Consommateurs').val();
            model.TypeBoisson = $('#TypeBoisson').val();
            model.NombreCuilliere = $('#NombreCuillere').val();
            model.PropreMug = $('#PropreMug').is(":checked");
            model.DerniereSelection = $('#DerniereSelection').is(":checked");
            
            
            $.ajax(
                {
                 
                url: '@Url.Action("Post","Consommation")',
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                type: 'post',
                    cache: false,
                    data: JSON.stringify(model),
                    success: function (data) { location.reload(); alert("Enjoy Your Drink / appréciez votre boisson"); },
                    error: function (f1, f2, f3) { location.reload(); }
            });

           

        }

    </script>



</head>

<body id="body">

    <fieldset id="infoForm">

        <div class="main-content">

            <div>

                <h1>Machine de Café </h1>

                <ul id="items" />

            </div>

            <div>
                @Html.LabelFor(m => Model.ConsommateurID)
                @Html.DropDownListFor(m => Model.ConsommateurID, new SelectList(new[] { "" }), "-Please seelect-", new { @class = "", onchange = "RecupererBadge()", @id = "Consommateurs" })
            </div>


            <div>
                @Html.LabelFor(m => Model.TypeBoisson)

                @Html.DropDownListFor(m => m.TypeBoisson, new SelectList(Enum.GetValues(typeof(TypeBoisson))), "-Please select-", new { @class = "", @id = "TypeBoisson" })

            </div>



            <div>
                @Html.LabelFor(m => Model.NombreCuilliere)

                @Html.DropDownListFor(m => m.NombreCuilliere, new SelectList(new List<int> { 1, 2, 3, 4, 5 }), "-Please select-", new { @class = "", @id = "NombreCuillere" })


            </div>

            <div>
                @Html.LabelFor(m => Model.PropreMug)
                @Html.CheckBoxFor(m => m.PropreMug, new { @class = "", @id = "PropreMug" })

            </div>

            <div>
                @Html.LabelFor(m => Model.DerniereSelection)
                @Html.CheckBoxFor(m => m.DerniereSelection, new { @class = "", @id = "DerniereSelection" })

            </div>

            <div>



                <input type="button" value="GO" onclick="ajouter();" />
                @*<input type="submit" />*@



            </div>





        </div>
    </fieldset>


</body>

</html>

CafeApplication.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CafeApplication.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CafeApplication.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @*<li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>*@
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - CafeApplication.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>